export enum actionTypes {
  // ****** app data actions ******
  SET_APP_DATA__START = 'SET_APP_DATA__START',
  SET_APP_DATA__SUCCESS = 'SET_APP_DATA__SUCCESS',
  SET_APP_DATA__FAIL = 'SET_APP_DATA__FAIL',
  // ****** position actions ******
  SET_POSITION__START = 'SET_POSITION__START',
  SET_POSITION__SUCCESS = 'SET_POSITION__SUCCESS',
  SET_POSITION__FAIL = 'SET_POSITION__FAIL',
  // ****** tokens filter actions ******
  ADD_FILTER = 'ADD_FILTER',
  CLEAR_FILTERS = 'CLEAR_FILTERS',
  // ****** addresses data actions ******
  SET_ADDRESSES_DATA__START = 'SET_ADDRESSES_DATA__START',
  SET_ADDRESSES_DATA__SUCCESS = 'SET_ADDRESSES_DATA__SUCCESS',
  SET_ADDRESSES_DATA__FAIL = 'SET_ADDRESSES_DATA__FAIL',

  // ****** headInfo data actions ******
  SET_HEADINFO_DATA__START = 'SET_HEADINFO_DATA__START',
  SET_HEADINFO_DATA__SUCCESS = 'SET_HEADINFO_DATA__SUCCESS',
  SET_HEADINFO_DATA__FAIL = 'SET_HEADINFO_DATA__FAIL',

  // ****** bundles data actions ******
  SET_BUNDLES_DATA__START = 'SET_BUNDLES_DATA__START',
  SET_BUNDLES_DATA__SUCCESS = 'SET_BUNDLES_DATA__SUCCESS',
  SET_BUNDLES_DATA__FAIL = 'SET_BUNDLES_DATA__FAIL',
}
