export enum actionTypes {
  // ****** app data actions ******
  SET_APP_DATA__START = 'SET_APP_DATA__START',
  SET_APP_DATA__SUCCESS = 'SET_APP_DATA__SUCCESS',
  SET_APP_DATA__FAIL = 'SET_APP_DATA__FAIL',
  // ****** position actions ******
  SET_POSITION__START = 'SET_POSITION__START',
  SET_POSITION__SUCCESS = 'SET_POSITION__SUCCESS',
  SET_POSITION__FAIL = 'SET_POSITION__FAIL',
  // ****** tokens filter actions ******
  ADD_FILTER = 'ADD_FILTER',
  CLEAR_FILTERS = 'CLEAR_FILTERS',
  // ****** addresses data actions ******
  SET_ADDRESSES_DATA__START = 'SET_ADDRESSES_DATA__START',
  SET_ADDRESSES_DATA__SUCCESS = 'SET_ADDRESSES_DATA__SUCCESS',
  SET_ADDRESSES_DATA__FAIL = 'SET_ADDRESSES_DATA__FAIL',

  // ****** apollo data actions ******
  SET_APOLLO_DATA__START = 'SET_APOLLO_DATA__START',
  SET_APOLLO_DATA__SUCCESS = 'SET_APOLLO_DATA__SUCCESS',
  SET_APOLLO_DATA__FAIL = 'SET_APOLLO_DATA__FAIL',

  // ****** atlas data actions ******
  SET_ATLAS_DATA__START = 'SET_ATLAS_DATA__START',
  SET_ATLAS_DATA__SUCCESS = 'SET_ATLAS_DATA__SUCCESS',
  SET_ATLAS_DATA__FAIL = 'SET_ATLAS_DATA__FAIL',

  // ****** blocks data actions ******
  SET_BLOCKS_DATA__START = 'SET_BLOCKS_DATA__START',
  SET_BLOCKS_DATA__SUCCESS = 'SET_BLOCKS_DATA__SUCCESS',
  SET_BLOCKS_DATA__FAIL = 'SET_BLOCKS_DATA__FAIL',

  // ****** bundles data actions ******
  SET_BUNDLES_DATA__START = 'SET_BUNDLES_DATA__START',
  SET_BUNDLES_DATA__SUCCESS = 'SET_BUNDLES_DATA__SUCCESS',
  SET_BUNDLES_DATA__FAIL = 'SET_BUNDLES_DATA__FAIL',

  // ****** hermes data actions ******
  SET_HERMES_DATA__START = 'SET_HERMES_DATA__START',
  SET_HERMES_DATA__SUCCESS = 'SET_HERMES_DATA__SUCCESS',
  SET_HERMES_DATA__FAIL = 'SET_HERMES_DATA__FAIL',

  // ****** home data actions ******
  SET_HOME_DATA__START = 'SET_HOME_DATA__START',
  SET_HOME_DATA__SUCCESS = 'SET_HOME_DATA__SUCCESS',
  SET_HOME_DATA__FAIL = 'SET_HOME_DATA__FAIL',

  // ****** transactions data actions ******
  SET_TRANSACTIONS_DATA__START = 'SET_TRANSACTIONS_DATA__START',
  SET_TRANSACTIONS_DATA__SUCCESS = 'SET_TRANSACTIONS_DATA__SUCCESS',
  SET_TRANSACTIONS_DATA__FAIL = 'SET_TRANSACTIONS_DATA__FAIL',
}
